name: todo_app
description: My todo app
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  isar: ^2.5.0
  hive: ^2.2.3
  provider: ^6.0.3
  dynamic_color: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Black.ttf
          weight: 900

        - asset: assets/fonts/Noto_Sans/NotoSans-BlackItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/Noto_Sans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Noto_Sans/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Noto_Sans/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Light.ttf
          weight: 300

        - asset: assets/fonts/Noto_Sans/NotoSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/Noto_Sans/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/Noto_Sans/NotoSans-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Noto_Sans/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Noto_Sans/NotoSans-Thin.ttf
          weight: 100

        - asset: assets/fonts/Noto_Sans/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
